# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='post',
            name='story',
            field=models.TextField(blank=True, default=''),
        ),
    ]
