# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_auto_20171202_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='social_app.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('0', 'freshman'), ('1', 'sophomore'), ('2', 'junior'), ('3', 'senior')], default='0', max_length=1),
        ),
    ]
