# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_auto_20171202_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='experiences',
            field=models.ManyToManyField(to='social_app.Experience'),
        ),
    ]
