# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0011_auto_20171202_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_app.Creator')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='social_app.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='social_app.Experience'),
        ),
        migrations.AddField(
            model_name='liketable',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_app.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='liketable',
            unique_together=set([('creator', 'post')]),
        ),
    ]
